steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t', 'asia.gcr.io/$PROJECT_ID/$_IMG_NAME:$_IMG_TAG',
          '-f', 'Dockerfile',
          '.'
          ]
images: [
        'asia.gcr.io/$PROJECT_ID/$_IMG_NAME:$_IMG_TAG'
        ]
